### ISSUE TITLE
migrate to python 3.8

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metadig-py#7]
currently this library depends on 2.7. There will be a couple of changes needed to the existing code, I'll describe them specifically here if needed when I dig into it

**Comment by jeanetteclark** [comment]
okay so turns out the reason why this is written the way that it is, is because this is a jython library not a python library. Jython is Python 2.7, not 3. This also explains why the library uses setuptools etc and not poetry. 

I'm not totally sure what the options are here. Python checks currently running in `metadig-engine` use a couple functions from this library, so jettisoning jython all together would be a big refactor for many checks. However, down the road, depending on jython could cause us problems since it won't allow us to do a whole lot of python analysis-type things (numpy is not available for jython, for example).

Thoughts @mbjones?

**Comment by mbjones** [comment]
I agree with your assessment of the relative difficulty. Getting rid of Jython is a good long-term goal. But there are also complications of trying to pass data through less reliable mechanisms -- the approach we are using in Java to R is also pretty convoluted. Let's discuss alternatives on our next design call.
